/* eslint-disable @typescript-eslint/no-unused-vars */
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import About from "@/components/About";
import Work from "@/components/Work";
import Contact from "@/components/Contact";
import TopButton from "@/components/TopButton/TopButton";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Header />
        <div className={styles.topImageWrapper}>
          <Image
            src="/green.JPG" // publicフォルダにある画像へのパス
            alt="Top Image"
            width={1200} // 画像の幅
            height={400} // 画像の高さ
            layout="responsive" // 画像をレスポンシブに表示
          />
          <div className={styles.textOverlay}>
            <div className={styles.ellipseBackground}></div>
            <p>心地よい場所へ</p><p>めぐる、つなぐ</p>
          </div>
        </div>
        <div id="about">
          <About />
        </div>
        <div id="works">
          <Work />
        </div>
        <div id="contact">
          <Contact />
        </div>
        <TopButton />
        <Footer />
      </div>
    </>
  );
}
